services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: promocode
      MYSQL_DATABASE: promocode
      MYSQL_USER: promocode
      MYSQL_PASSWORD: promocode
    volumes:
      - ./docker/database:/var/lib/mysql
    ports:
      - "8306:3306"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
